### ISSUE TITLE
Installation NetFx4 fail?

### ISSUE THREAD

**Issue by guillaumededrie** [joefitzgerald/packer-windows#118]
Hi,
I'm trying to create a W7 VM using these json:
```
{
  "builders": [
    {
      "type": "virtualbox-iso",
      "iso_url": "http://care.dlservice.microsoft.com/dl/download/evalx/win7/x64/EN/7600.16385.090713-1255_x64fre_enterprise_en-us_EVAL_Eval_Enterprise-GRMCENXEVAL_EN_DVD.iso",
      "iso_checksum_type": "md5",
      "iso_checksum": "1d0d239a252cb53e466d39e752b17c28",
      "headless": false,
      "boot_wait": "2m",
      "ssh_username": "vagrant",
      "ssh_password": "vagrant",
      "ssh_wait_timeout": "8h",
      "shutdown_command": "shutdown /s /t 10 /f /d p:4:1 /c \"Packer Shutdown\"",
      "guest_os_type": "Windows7_64",
      "disk_size": 61440,
      "floppy_files": [
        "./answer_files/7/Autounattend.xml",
        "./scripts/dis-updates.ps1",
        "./scripts/microsoft-updates.bat",
        "./scripts/win-updates.ps1",
        "./scripts/openssh.ps1",
        "./scripts/oracle-cert.cer"
      ],
      "vboxmanage": [
        [
          "modifyvm",
          "{{.Name}}",
          "--memory",
          "2048"
        ],
        [
          "modifyvm",
          "{{.Name}}",
          "--cpus",
          "2"
        ]
      ]
    }
  ],
  "provisioners": [
    {
      "type": "shell",
      "remote_path": "/tmp/script.bat",
      "execute_command": "{{.Vars}} cmd /c C:/Windows/Temp/script.bat",
      "scripts": [
        "./scripts/vm-guest-tools.bat",
        "./scripts/vagrant-ssh.bat",
        "./scripts/disable-auto-logon.bat",
        "./scripts/enable-rdp.bat",
        "./scripts/compile-dotnet-assemblies.bat",
        "./scripts/compact.bat",
        "./scripts/chocolatey.bat"
      ]
    }
  ],
  "post-processors": [
    {
      "type": "vagrant",
      "keep_input_artifact": false,
      "output": "windows_7_{{.Provider}}.box",
      "vagrantfile_template": "vagrantfile-windows_7.template"
    }
  ]
}
```

I didn't make any changes any of `/scripts/` files except I disable Window Update.

When I launch Packer.io, the VM creation doesn't finish, and seems to fail on `NetFx` installation: 
```
    virtualbox-iso: Installing chocolatey on this machine
    virtualbox-iso: Creating ChocolateyInstall as an Environment variable (targeting 'Machine') and setting it to 'C:\ProgramData\chocolatey'
    virtualbox-iso: We are setting up the Chocolatey repository for NuGet packages that should be at the machine level. Think executables/application packages, not library packages.
    virtualbox-iso: That is what Chocolatey NuGet goodness is for. The repository is set up at 'C:\ProgramData\chocolatey'.
    virtualbox-iso: The packages themselves go to 'C:\ProgramData\chocolatey\lib' (i.e. C:\ProgramData\chocolatey\lib\yourPackageName).
    virtualbox-iso: A shim file for the command line goes to 'C:\ProgramData\chocolatey\bin' and points to an executable in 'C:\ProgramData\chocolatey\lib\yourPackageName'.
    virtualbox-iso:
    virtualbox-iso: Creating Chocolatey NuGet folders if they do not already exist.
    virtualbox-iso:
    virtualbox-iso: Copying the contents of 'C:\Windows\Temp\chocolatey\chocInstall\tools\chocolateyInstall' to 'C:\ProgramData\chocolatey'.
    virtualbox-iso: PATH environment variable does not have C:\ProgramData\chocolatey\bin in it. Adding...
    virtualbox-iso: Downloading NetFx4.0 64 bit
    virtualbox-iso: from 'http://download.microsoft.com/download/5/6/2/562A10F9-C9F4-4313-A044-9C94E0A8FAC8/dotNetFx40_Client_x86_x64.exe'
    virtualbox-iso: Installing NetFx4.0...
```

How can I debug this issue?

Regards
